### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by paulthadev** [mohammedshahid096/Learning_Management_MERN#1]
@mohammedshahid096 @ranupl 
I would love to contribute on this project, can i get an example of how the env file is structured?

**Comment by mohammedshahid096** [comment]
> @mohammedshahid096 @ranupl 
> I would love to contribute on this project, can i get an example of how the env file is structured?

Yaa sure by the end of the day will add instructions for set-up in readme

**Comment by paulthadev** [comment]
> > @mohammedshahid096 @ranupl
> > I would love to contribute on this project, can i get an example of how the env file is structured?
> 
> Yaa sure by the end of the day will add instructions for set-up in readme

Thanks, I have seen the recent update and ENV Structure in the update [README ](https://github.com/mohammedshahid096/Learning_Management_MERN/blob/main/Frontend/README.md)
